#Expyriment 0.10.0 (Python 3.8.10), .xpe-file, coding: cp1252
#date: Sat Sep 20 2025 14:31:17
#sha1: 975ac6
#modules: 
#display: size=(1920, 1080), window_mode=False, open_gl=2
#os: uname_result(system='Windows', node='Omrizt17', release='10', version='10.0.26100', machine='AMD64', processor='Intel64 Family 6 Model 140 Stepping 2, GenuineIntel')
Time,Type,Event,Value,Detail,Detail2
5497,stderr,received,'Traceback (most recent call last):'
5497,stderr,received,'  File "C:\\Users\\omriz\\OneDrive\\Documents\\M1 CogSup\\Experimental_Approach\\Programming\\Assignments\\Week-2\\Exercises\\labeled_shapes.py", line 16, in <module>'
5498,stderr,received,'    vertex_list=geometry.vertices_regular_polygon(3, SIZE),'
5498,stderr,received,"NameError: name 'geometry' is not defined"
